
import { InfoObject } from '../types';

export const contentDhv201Input: InfoObject = { title: "Från Elleverantör", attributes: [{ attribute: "Address", description: "Gatuadress, postnummer, ort.", article: "M" }] };
export const contentDhv201Output: InfoObject = { title: "Till Elleverantör", attributes: [{ attribute: "Accounting Point ID", description: "Identifierat ID.", article: "M" }, { attribute: "Message", description: "Information om adressen inte är unik.", article: "C" }] };
export const contentDhv202Input: InfoObject = { title: "Från Elleverantör", attributes: [{ attribute: "Accounting Point ID", description: "ID på anläggningen.", article: "M" }] };
export const contentDhv202Output: InfoObject = { title: "Till Elleverantör", attributes: [{ attribute: "Master Data", description: "Teknisk information om anläggningen.", article: "M" }] };
export const contentDhv203Output: InfoObject = { title: "Till Elleverantör", attributes: [{ attribute: "Customer Info", description: "Namn, Personnummer (efter samtycke).", article: "M" }, { attribute: "Metering Point Data", description: "Anläggningsinformation.", article: "M" }, { attribute: "Contract Data", description: "Nuvarande avtalsinformation (om relevant).", article: "M" }] };
export const contentDhv211Input: InfoObject = { title: "Från Elleverantör", attributes: [{ attribute: "Accounting Point ID", description: "ID på anläggningen.", article: "M" }, { attribute: "Start Date", description: "Datum för inflytt/byte.", article: "M" }, { attribute: "Customer ID", description: "Person/Org-nummer.", article: "M" }] };
export const contentDhv213Input: InfoObject = { title: "Från Elleverantör", attributes: [{ attribute: "Accounting Point ID", description: "ID på anläggningen.", article: "M" }, { attribute: "End Date", description: "Datum för utflytt.", article: "M" }] };
export const contentDhv212Input: InfoObject = { title: "Från Befintlig Elleverantör", attributes: [{ attribute: "Accounting Point ID", description: "ID på anläggningen.", article: "M" }, { attribute: "Rejection Reason", description: "Orsak till avvisandet.", article: "M" }] };
export const contentDhvCancelInput: InfoObject = { title: "Från Elleverantör", attributes: [{ attribute: "Original Transaction ID", description: "Referens till den process som ska ångras.", article: "M" }, { attribute: "Reason", description: "Orsak till ångerrätt.", article: "O" }] };
export const contentDhv240Output: InfoObject = { title: "Till Elleverantör", attributes: [{ attribute: "Status", description: "Pending existing customer / Pending under construction.", article: "M" }, { attribute: "Reason", description: "Orsak till vänteläge.", article: "M" }] };
export const contentDhv511Input: InfoObject = { title: "Från Elleverantör", attributes: [{ attribute: "Customer ID", description: "Kundens ID.", article: "M" }, { attribute: "Changes", description: "Ändrade uppgifter (t.ex. vid dödsbo).", article: "M" }] };
export const contentDhv514Input: InfoObject = { title: "Från Elleverantör", attributes: [{ attribute: "Accounting Point ID", description: "ID på anläggningen.", article: "M" }, { attribute: "Contract ID", description: "Leverantörens avtals-ID.", article: "M" }, { attribute: "Start Date", description: "Avtalsstart.", article: "M" }, { attribute: "End Date", description: "Avtalsslut (om tidsbegränsat).", article: "O" }, { attribute: "Type", description: "Avtalstyp.", article: "M" }] };
export const contentDhvRequestContractInput: InfoObject = { title: "Från Aktör", attributes: [{ attribute: "Accounting Point ID", description: "ID på anläggningen.", article: "M" }, { attribute: "Contract ID", description: "Specifikt avtal (valfritt).", article: "O" }] };
export const contentDhvContractOutput: InfoObject = { title: "Till Aktör", attributes: [{ attribute: "Contract Data", description: "Detaljer om avtalet (Start, Slut, Typ).", article: "M" }] };
export const contentDhvRequestCustomerInput: InfoObject = { title: "Från Aktör", attributes: [{ attribute: "Customer ID", description: "Person/Org-nummer.", article: "M" }] };
export const contentDhvCustomerOutput: InfoObject = { title: "Till Aktör", attributes: [{ attribute: "Customer Info", description: "Namn, Adress, Kontaktuppgifter.", article: "M" }] };
export const contentDhv563Input: InfoObject = { title: "Från Nätägare", attributes: [{ attribute: "Accounting Point ID", description: "ID på anläggningen.", article: "M" }] };
export const contentDhv563Output: InfoObject = { title: "Till Nätägare", attributes: [{ attribute: "Delivery Structure", description: "Aktiva leveranser och aktörer.", article: "M" }] };
export const contentDhvGenericOutput: InfoObject = { title: "Till Aktör", attributes: [{ attribute: "Response", description: "Bekräftelse eller felmeddelande.", article: "-" }] };
export const contentDhvGenericInput: InfoObject = { title: "Från System", attributes: [{ attribute: "Event ID", description: "Händelse-ID", article: "M" }] };
